<template>
  <div>
    <Header></Header>
    <Presentation></Presentation>
    <Skiils></Skiils>
    <Certificate></Certificate>
    <Experiences></Experiences>
    <Contact></Contact>
  </div>
</template>
